### ISSUE TITLE
add an example of how to put multiple suites in a module and use nested suites.

### ISSUE THREAD

**Issue by johntrandall** [theintern/intern-examples#13]
add an example of how to put multiple suites in a module and use nested suites.

Tutorial states the following, but doesn't show a syntax example. None of these examples do either.

    These pieces can be visualized in a hierarchy, like this:
    
    * test module
      * test suite
        * test suite
          * test case
            * ...
          * ...
        * test case
          * assertion
          * assertion
          * ...
        * ...
      * test suite
      * ...
    * test module
    * ...

**Comment by csnover** [comment]
There are now examples in the [user guide](https://theintern.github.io/intern/#interface-overview) for the test interfaces that support nesting.
