### ISSUE TITLE
AngularJSExample does not work as configured

### ISSUE THREAD

**Issue by agray** [theintern/intern-examples#15]
As of the latest commit at time of this writing the AngularJS example does not work as configured.

The tests run on SauceLabs however errors are thrown in the Jenkins console and the build fails. Jenkins is running as Windows service on a Windows 2012 VM, directly connected to the internet, no proxy.

The Jenkins builds steps are:

**Command 1**  

    cd angularjs-example  
    npm install bower -g

**Command 2**  

    cd angularjs-example  
    npm install

**Command 3**  

    cd angularjs-example  
    bower install

**Command 4**  

    cd angularjs-example  
    .\node_modules\.bin\intern-runner config=tests\intern.js reporters=runner reporters=junit reporters=cobertura

If only the non-functional tests are executed there are 11 tests.

11 tests execute on SauceLabs and are reported as PASSED

7 instances of the following appear in the Jenkins console, 

`undefined: Failed to load module angular/angular from /angular/angular.js (parent: *33) at http://localhost:9000/__intern/node_modules/dojo/dojo.js:731`

which appear to be at least part of the issue.

In some cases the next line of the error in the Jenkins console is

`at .run/window.onerror <__intern\lib\realClient.js:57>`

in other cases it is:

` at HTMLScriptElement.handler <__intern\node_modules\dojo\dojo.js:733:13>`

**Comment by dylans** [comment]
I'm unable to reproduce this against SauceLabs, or a local Selenium setup, with Intern 2.2.2, Selenium 2.45.0, Firefox 36, and Chrome 41.

Please re-open if you're still able to reproduce, and if so, please specify which browser(s) seem to be the issue here.

**Comment by agray** [comment]
Could you please advise how you are configuring the Jenkins build.

What are the steps.

Bit of a noob with Grunt and NPM.

Thank you
