### ISSUE TITLE
Add 'page objects' / custom Command examples

### ISSUE THREAD

**Issue by necolas** [theintern/intern-examples#16]
This would be a useful way to introduce people to these patterns.

**Comment by kevin-miles** [comment]
+1
if i can get a clean pageobject setup ill post one. having issues with wiki example, so this would have helped me as well :)

**Comment by necolas** [comment]
@kevin-miles here's an example of the approach i'm using (snover helped me out): https://gist.github.com/necolas/3dcb09f5a4cdaffc5b51

**Comment by kevin-miles** [comment]
thanks @necolas !

**Comment by vladikoff** [comment]
Another example here: https://gist.github.com/neonstalwart/48667ed7bce70b8a5f38

**Comment by csnover** [comment]
Page objects are now described in the [page objects section](https://theintern.github.io/intern/#page-objects) of the user guide.
