### ISSUE TITLE
"Full" example is missing from the repo.

### ISSUE THREAD

**Issue by baloneysandwiches** [theintern/intern-examples#20]
The readme says:

> "Full SauceLabs Example

>The goal of this example is to test as many browsers on SauceLabs as possible. This example might use a lot of your available minutes on SauceLabs and it is not recommended to run it.

>See travis-ci-example/test/teststack_full.js.

but that file(path) doesn't actually exist.

**Comment by dylans** [comment]
Looks like a very old URL, and this test does not exist any more. It was probably a bad idea to have an example that would by default exhaust your SauceLabs minutes.

To run with SauceLabs, you basically are better off following the instructions at https://theintern.github.io/intern/#hosted-selenium . I'll update the info in the readme.

**Comment by dylans** [comment]
https://github.com/theintern/intern-examples/pull/21
