### ISSUE TITLE
Backbone example issue

### ISSUE THREAD

**Issue by kimek** [theintern/intern-examples#41]
I'm new to The Intern. 
Any chance why only backbone doesn't work from those examples ?

> backbone-intern-example@0.2.0 test /home/delta/intern/intern-examples-master/backbone-example
> intern-runner config=tests/intern

`
Error: Failed to load module intern/lib/reporters/Lcovhtml from /home/delta/intern/intern-examples-master/backbone-example/node_modules/intern/lib/reporters/Lcovhtml.js (parent: *26)
  at ReadFileContext.callback  <node_modules/dojo/loader.ts:831:119>
  at FSReqWrap.readFileAfterOpen [as oncomplete]  <fs.js:303:13>
npm ERR! Test failed.  See above for more details.
`

npm 4.5.0 (global)
ubuntu 16.10
intern-cli recent ones

**Comment by dylans** [comment]
For some reason you're missing the Lcovhtml reporter (which is pretty obvious from the error message), that is used for code coverage analysis. Could you be a bit more explicit in the steps you followed for installation?

**Comment by kimek** [comment]
true :), good point as I forgot that I'm on Linux and here everythink is better. It's case sensitive and lcovhtml is 
`-rw-r--r-- 1 delta delta   601 Mar 21 19:51 LcovHtml.js`

**Comment by dylans** [comment]
Ah, that makes sense... thanks for the PR.

Closed via #42.
