### ISSUE TITLE
dojo-example dojo/text  plugin failed to load

### ISSUE THREAD

**Issue by nicolasiac** [theintern/intern-examples#48]
Downloaded the project , run npm install and then
` .\node_modules\.bin\intern-client config=tests/intern`
I get the error
dojo/text plugin failed to load because loader does not support getText

I see that in the package.json of intern 3.4.6 there is dependency for dojo 2.0.0-alpha.7
is this the problem?

**Comment by kitsonk** [comment]
What version of Node.js are you using?  Also, it appears you might be running on Windows, if so what version?

**Comment by nicolasiac** [comment]
For some unexplained reason now it is working. I don't remember what I did differently (several npm install/uninstall) but the error was consistent in all the projects I tried to test it.
Do we have to install something globally?

**Comment by kitsonk** [comment]
No.
